### PR TITLE
issue #297: added an overload for GeoJsonReader.readToGeometryRDD wit…

### PR DESCRIPTION
**Pull request by AntonPeniaziev**
…h additional parameter to skip invalid geometries in result RDD

## Is this PR related to a proposed Issue?
#297 
## What changes were proposed in this PR?
Add an option to create an RDD from geoJson, skipping invalid geometries
## How was this patch tested?
Added a test with both valid and invalid geometries.
## Did this PR include necessary documentation updates?
No

### CODE REVIEW

**Comment by AntonPeniaziev** [comment]
Hi @jiayuasu  ,

1. Regarding CI fail, I have a technical question: I've added a json file for test into core\target\test-classes that is git ignored, so I've pushed my file with --force. I indeed can see the file pushed successfully https://github.com/AntonPeniaziev/GeoSpark/commit/c483fd505b6e8e66e70db42427f7a2e0c38d9b2a 

However, the CI still can't see it that is I've got an error GeoJsonReaderTest.onceExecutedBeforeAll:56 NullPointer .

Can you please elaborate on how should I add new test sources to ignored directory?

2.  The objective is not to validate the invalid geometries rather give to user an option to build and RDD from geoJson that will contain only **topologically** valid geometries. Note that this cannot be done with ST_Isvalid expression, since it receives single geometry, when GeoJsonReader.readToGeometryRDD receives a path to file. Theoretically there is an option to make a filter,  somehow with lambda in java when using
val isvalidop = new IsValidOp(geometry)
    isvalidop.isValid

but I haven't succeed to do so due to Java version issues.  I think public API should be more friendly in that way.

3. Another topic I haven't covere here is huge geoJsons with **invalid syntax** geometry.
I've seen @netanel246 's issue #291 relates it. 
We actually have a use case with a big GeoJson (ten's of millions rows) that contains few geometries with invlid syntax, for example - a polygon that is not closed or a polygon with zero area, like
POLYGON((a, b, a))
Of course we are not talking about total syntax mess, but there are GEO processing tools in the market that can create those kind of **syntactically** invalid geometries that I've mentioned above and we need to deal with them. 

I've managed to solve it with some try-catch warappers around each readGeometry.  Do you think it's worse another issue opened or I can just edit a title a bit?

Regards,

Anton

**Comment by jiayuasu** [comment]
@AntonPeniaziev 
Got your point.

Since GeoSpark has a bunch of different format readers: GeoJSON, Shapefile, WKT, WKB, HDF...

So I recommend that, don't do validation for GeoJSON.

Instead, please create a new function in SpatialRDD:
https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java#L118

called RemoveInvalidGeometry(). It checks rawSpatialRDD and filters out all geometries whose isvalidop.isValid is false.

This provides a very generic API for all input formats. So the user first loads all geometries to rawSpatialRDD and then call "RemoveInvalidGeometry" to remove invalid geometries.

Most importantly, this will help all other users.

Regarding your Point3, we probably need to have a separate PR to discuss.

Thank you again for your effort!

Jia

**Comment by AntonPeniaziev** [comment]
@jiayuasu ,
Regarding RemoveInvalidGeometry function
I've looked at SpatialRdd code and I don't see any proper way to implement it since after filtering invalid geometries index becomes obsolete and calculating new one could sometimes be against users intentions. Like it was mentioned in Geospark paper there are cases when absence of index improved the performance.

The only aternative I can think about is implemeting <Format>Reader for each type like GeoJsonReader,
and use the functionality I've already implemented in FormatMapper (use allowInvalidGeometries flag)

Tell me please what do you think is better approach.

Regards,

Anton

**Comment by jiayuasu** [comment]
@AntonPeniaziev OK.  Understand, it makes sense. Let me first accept this PR and then figure out how to do the same check for other formats.

In your another PR for Issue https://github.com/DataSystemsLab/GeoSpark/issues/299, please make sure you differentiate invalidTopologyGeom and invalidSyntaxGeom in the overload API, otherwise the user may feel confused.

**Pull request merged**
